# Generated by Django 5.0.1 on 2024-04-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="audios/"),
        ),
    ]
