# Generated by Django 5.0.1 on 2024-04-07 05:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_video_audio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="audio",
        ),
    ]
